name: Kaggle Badges

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0"  # Every Sunday at midnight UTC
  workflow_dispatch:  # Manual trigger

jobs:
  create-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - name: Install Puppeteer browser
        run: npx puppeteer browsers install chrome@131.0.6778.85
      
      - name: Generate Kaggle Badges
        uses: spider-man-tm/kaggle-badges@v1.3.0
        with:
          user_name: kakuteki
      
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./kaggle-badges/* ./kaggle-plates/* || true
          git diff --staged --quiet || git commit -m "Update Kaggle badges"
          git push || true
